### ISSUE TITLE
Error opening grammar file - Version4

### ISSUE THREAD

**Issue by Therindor** [lakiw/pcfg_cracker#11]
Hey, looks like grammar_io.py tries to open path `grammar/grammar.txt`, however the directory should be `Grammar/grammar.txt`.

So I guess the referenced line should be changed from:

`filename = os.path.join(base_directory,"grammar","grammar.txt")`
to:
`filename = os.path.join(base_directory,"Grammar","grammar.txt")`

https://github.com/lakiw/pcfg_cracker/blob/8fd4ce9a748e0f36ccead9943a3a1aa8a9d6024f/lib_guesser/grammar_io.py#L134

**Comment by lakiw** [comment]
Awesome bug report. Thank you very much for trying my code, finding the bug, finding the solution, and writing a great issue that made it easy for me to verify what you were seeing. I just pushed a fix in https://github.com/lakiw/pcfg_cracker/commit/9d3de3c3ed008eda740ba5829bfbe4e9160be6a5. That fix will be pushed to master once the rest of 4.0 goes live. 

This highlights that I need to test on more machines, since my main dev box doesn't care about folder capitalization. I'm going to close this current issue, but if anything else pops up please don't hesitate to either reopen this one or create a new issue, as once again I really appreciate your help.
