### ISSUE TITLE
How do I apply a training set to a specific set of passwords

### ISSUE THREAD

**Issue by spencerhethcoxwib18** [lakiw/pcfg_cracker#20]
How do I apply a training set to a specific set of passwords? Let's say I want to see password options based on a trained model.

**Comment by lakiw** [comment]
I apologize since I don't think I fully understand your question. If you are wondering how to train on a specific set of passwords to analyze their features you can run:

python3 trainer.py -t INPUT_PASSWORD_LIST -r NEW_RULESET

All the information about the passwords will be saved in ./rules/NEW_RULESET

Does this help? Or were you asking about something else?

**Comment by lakiw** [comment]
Since there has been no follow up questions, I'm closing this issue.
