### ISSUE TITLE
Performance impact new next algorithm

### ISSUE THREAD

**Issue by zyronix** [lakiw/pcfg_cracker#41]
When playing with version 4.6 of the guesser, the next algorithm because quite a bottle neck. 

I sometimes let PCFG generate some candidates and then just offload them to some computing platform and start noticing that PCFG is roughly 5 to 10 times slowers (depending on how long you let it generate).

Examples:
```
<version> <n candidates> <generating time>
Old version:  2.000.000: 1m59.451s
New version:  2.000.000: 11m40.378s

Old version: 1.000.000: 1m3.373s
New version 1.000.000: 5m26.956s
```

For me this make PCFG unusable in my current workflow. Simple solution would be to just use the old version :P. But I understand why the new next was implemented, but does it make sense to have two next implementations? One that fully / stuffs your memory and the current memory low implementation (make that one default)?

Random walk is not an options for me, because the quality of candidates is quite bad when using the random walk.

Would you mind me implementing a commandline parameter that allows you to use the old next algorithm?

**Comment by lakiw** [comment]
Thanks for highlighting this! There were a couple of changes recently to the guess generation algorithm so I'd like to better understand the root cause of this, which is another way of saying I'm a bit hesitant to just include a switch between the two guess generation algorithms.  I'll take ownership that I'm running way behind on a couple of other things I said I'd do for updating documentation and adding a few more tweaks to these newer changes. I'll also be up front that with the holidays coming up I will probably be pushing off most changes/reviews/etc into the new year. That's to say that your strategy of using the older version is probably the best short term option (and I feel really bad about saying that!) and that I don't want you to waste your holiday time making that switch just for me to not review it in a timely fashion.

**Comment by lakiw** [comment]
At least for me, it seems like the performance issue only occurs when I use the "-n" flag to limit output. For example:

laki@DESKTOP-H75K7GJ:/mnt/c/github/pcfg_cracker$ time python3 pcfg_guesser.py | head -10000000 > /dev/null
Version: 4.5

Loading Ruleset: Default

The consumer, probably the password cracker, has stopped
accepting input.
Halting guess generation and exiting

real    0m43.596s
user    0m42.078s
sys     0m0.422s


laki@DESKTOP-H75K7GJ:/mnt/c/github/pcfg_cracker$ time python3 pcfg_guesser.py | head -10000000 > /dev/null
Version: 4.6

Loading Ruleset: Default

Starting to generate password guesses
Press [ENTER] to display a status output
Press 'q' [ENTER] to exit

The consumer, probably the password cracker, has stopped
accepting input.
Halting guess generation and exiting

real    0m49.139s
user    0m45.938s
sys     0m0.563s

laki@DESKTOP-H75K7GJ:/mnt/c/github/pcfg_cracker$ time python3 pcfg_guesser.py | head -100000000 > /dev/null
Version: 4.6

Loading Ruleset: Default

The consumer, probably the password cracker, has stopped
qaccepting input.
Halting guess generation and exiting

real    32m55.545s
user    7m15.156s
sys     0m1.813s

**Comment by lakiw** [comment]
I'm curious if this is your experience as well? I fully realize "it works on my machine" is not an acceptable answer ;p. Regardless, this points to needing to optimize the guess limit checks among other possible things.

**Comment by zyronix** [comment]
That is so interesting, I guess indeed that the problem is in the limit. However in the commit (4d70727d8d71a0fa7433da9de31c930f39861b33) of @Wineh the performance impact is not there, it happens after your changes.

**Comment by zyronix** [comment]
Found what this was causing. I saw all kind of weird behaviors. But with the changes that you made to the pull request, you wrongly placed a keyword argument as a positional; causing the limit to be passed as the variable that trigged the honeyword guesser. Thus:
Performance sucked when using limit
Honeyword was being used instead of the normal guesser. I will create a pull request with the bug fix.
