### ISSUE TITLE
Error parsing the probabilities from the training file

### ISSUE THREAD

**Issue by matlink** [lakiw/pcfg_cracker#7]
Sometimes I got this error when loading large files: 
`Error parsing the probabilities from the training file`

How can I fix this?

**Comment by matlink** [comment]
Having a quick look at `file_io.py`, it seems that you read probabilities from a tab separated file, which explains the current issue.

**Comment by lakiw** [comment]
I pushed what I thought was a fix for this about 14 days ago with version 3.3 Beta. Is that the version you are running right now. It wouldn't be the first time I thought I fixed a bug and didn't so if you are still seeing it I'll look into it more.  The fix was on line 252 of training_data.py:

 if "\t" in input_password:
            return RetType.IS_FALSE

Basically I was trying to reject any password with a tab in it. I figured that wasn't too big a deal since most password input boxes don't support tabs.

If there is a need for tabs in password guesses please let me know and I can encode them differently.

**Comment by lakiw** [comment]
Closing the issue. If this is still a problem I can re-open it.
